- name: create config dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: 
    - /etc/modules-load.d
    - /etc/sysctl.d
    - /etc/containerd

- name: write k8s modules
  ansible.builtin.copy:
    src: modules-load.conf
    dest: /etc/modules-load.d/k8s.conf
    mode: '0644'

- name: load k8s modules
  ansible.builtin.command: "modprobe {{ item }}"
  changed_when: false
  loop: 
    - overlay

- name: write k8s sysctl
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
  notify: apply sysctl

- name: configure containerd
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: restart containerd
