cluster_name: gentoo-k8s
kubeadm_api_port: 6443
pod_cidr: 172.16.0.0/16
service_cidr: 172.20.0.0/16
cilium_version: 1.19.6
# metallb_pool: 10.30.3.200-10.30.3.220  # TODO: unused until a metallb or cilium LB-IPAM role consumes it
kubeadm_skip_phases:
  - addon/kube-proxy
