Vagrant.configure("2") do |config|
  config.vm.box = "k8s-node-ops-stage4"
  config.vm.box_url = "file://#{File.expand_path("k8s-node-ops-stage4.box", __dir__)}"
  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "%c"
  config.vm.allow_fstab_modification = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  nodes = {"k8s-cp1" => "192.168.56.101", "k8s-cp2" => "192.168.56.102", "k8s-cp3" => "192.168.56.103"}
  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.network "private_network", ip: ip
      node.vm.provider "libvirt" do |lv|
        lv.memory = 2048
        lv.cpus = 2
        lv.kernel = File.expand_path("vmlinuz", __dir__)
        lv.initrd = File.expand_path("initramfs", __dir__)
        lv.cmd_line = "root=/dev/vda rw console=ttyS0 systemd.hostname=#{name}"
      end

      # if name == "k8s-cp3"
      #   node.vm.provision "ansible" do |ansible|
      #     ansible.playbook = "../ansible/site.yml"
      #     ansible.inventory_path = "../ansible/inventory/vagrant.yml"
      #     ansible.limit = "k8s_nodes"
      #   end
      # end

    end
  end
end
