Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  nodes = {"k8s-cp1" => "192.168.56.101", "k8s-cp2" => "192.168.56.102", "k8s-cp3" => "192.168.56.103"}
  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end
end
