- name: configure kubelet service
  ansible.builtin.copy:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service
    mode: '0644'
  notify: reload systemd

- name: create kubelet service dropin dir
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    mode: '0755'

- name: configure kubeadm dropin
  ansible.builtin.copy:
    src: 10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    mode: '0644'
  notify: reload systemd

- name: enable kubelet
  ansible.builtin.systemd_service:
    name: kubelet
    enabled: true
