- name: create root kube config dir
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: link root kube config
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link
    force: true
