# init configs
- hosts: k8s_nodes
  tags: node-config
  roles:

    - role: containerd
      tags: containerd

    - role: kubelet
      tags: kubelet

    - role: keepalived
      tags: keepalived

- hosts: k8s_nodes
  tags: init
  roles:

    - role: kubeadm-init
      run_once: true
      tags: kubeadm-init

    - role: kubeadm-join-credentials
      tags: kubeadm-join-credentials

- hosts: k8s_nodes
  tags: join
  serial: 1
  roles:

    - role: kubeadm-join
      tags: kubeadm-join

- hosts: k8s_nodes
  tags: post-install
  gather_facts: false
  roles:

    - role: kubectl-config
      tags: kubectl-config

    - role: cilium
      run_once: true
      tags: cilium

    - role: control-plane-workloads
      tags: control-plane-workloads
