- hosts: k8s_nodes
  roles:
    - containerd
    - kubelet
    - keepalived

- hosts: k8s_nodes
  roles:
    - role: kubeadm-init
      run_once: true

- hosts: k8s_nodes
  roles:
    - kubeadm-join-credentials

- hosts: k8s_nodes
  serial: 1
  roles:
    - kubeadm-join
