- hosts: k8s_nodes[0]
  gather_facts: false
  vars:
    local_kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/{{ kubectl_context_name }}"
  tasks:
    - name: create local kube config dir
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.kube"
        state: directory
        mode: '0700'
      delegate_to: localhost

    - name: save kube config
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ local_kubeconfig }}"
        flat: true

    - name: secure local kube config
      ansible.builtin.file:
        path: "{{ local_kubeconfig }}"
        state: file
        mode: '0600'
      delegate_to: localhost
